version: '3.2'
services:
  mongoserver:
    container_name: mongo_server
    image: mongo:latest
    ports:
      - 27017:27017
  postgreserver:
    container_name: postgres_server
    image: postgres:9.5
    volumes:
      - /var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_USER=jackk
      - POSTGRES_DB=scrabble
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
  scrabble:
    build:
      context: ./
      dockerfile: Dockerfile
    image: scrabble
    links:
      - postgreserver
      - mongoserver
    ports:
      - 8080:8080
    depends_on:
      - mongoserver
      - postgreserver

